### PR TITLE
E0TMzBJx Front cleaning

### PR DESCRIPTION
**Pull request by YevgenChop**
Fixed issues

### CODE REVIEW

**Comment by YevgenChop** [comment]
[Display FG/TD drawer](https://trello.com/c/tCEPSSf7/75-display-fg-td-drawer)

**Comment by YevgenChop** [comment]
[Provenance](https://trello.com/c/JKdNQ6FQ/76-provenance)

**Comment by YevgenChop** [comment]
[Front cleaning 2](https://trello.com/c/E0TMzBJx/78-front-cleaning-2)

**Comment by YevgenChop** [comment]
[Front cleaning 2](https://trello.com/c/E0TMzBJx/78-front-cleaning-2)

**Comment by YevgenChop** [comment]
[Version dropdown bug](https://trello.com/c/A0AYrg0I/80-version-dropdown-bug)

**Comment by YevgenChop** [comment]
[Navigate through commits](https://trello.com/c/LFLja9A0/81-navigate-through-commits)

**Comment by YevgenChop** [comment]
[Keywords](https://trello.com/c/xKfWLGld/83-keywords)

**Review by giardiv — APPROVED** [review]

**Pull request merged**
